"""adding a pitch table and relationship

Revision ID: 4c1709bad01a
Revises: 946fc50ac41b
Create Date: 2019-09-20 16:16:55.610844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1709bad01a'
down_revision = '946fc50ac41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitchTitle', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('pitchWrite', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('posted', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('userId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'users', ['userId'], ['id'])
    op.drop_column('pitches', 'name')
    op.drop_constraint('users_pitch_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_pitch_id_fkey', 'users', 'pitches', ['pitch_id'], ['id'])
    op.add_column('pitches', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'userId')
    op.drop_column('pitches', 'posted')
    op.drop_column('pitches', 'pitchWrite')
    op.drop_column('pitches', 'pitchTitle')
    # ### end Alembic commands ###
