"""Initial Migration

Revision ID: dbf3106de8c6
Revises: e0a2e9d39fbe
Create Date: 2019-09-22 16:06:18.032066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf3106de8c6'
down_revision = 'e0a2e9d39fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('pitches', 'downVotes')
    op.drop_column('pitches', 'pitchCategory')
    op.drop_column('pitches', 'upVotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('upVotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('pitchCategory', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('downVotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
