"""Initial Migration

Revision ID: e0a2e9d39fbe
Revises: 4c1709bad01a
Create Date: 2019-09-21 10:17:15.667734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a2e9d39fbe'
down_revision = '4c1709bad01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('pitchId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitchId'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitches', sa.Column('downVotes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('pitchCategory', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('upVotes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=5000), nullable=True))
    op.add_column('users', sa.Column('posted', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'posted')
    op.drop_column('users', 'bio')
    op.drop_column('pitches', 'upVotes')
    op.drop_column('pitches', 'pitchCategory')
    op.drop_column('pitches', 'downVotes')
    op.drop_table('comments')
    # ### end Alembic commands ###
